services:
  backend:
    build: ./backend
    container_name: fpc-playground-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
  frontend:
    image: nginx:latest
    container_name: fpc-playground-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
